project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!/student-versions/"
    - "!/solutions/"
    - "!/exams/"
    - "!/course-info/stud-info/"
    - "!/project/"
    - "!/handouts/"
    - "!/quiz/"

website:
  page-navigation: true
  title: "Introduction to Statistical Computing in R"
  description: "Homepage for STAT 331/531 at Cal Poly Spring 2025"
  site-url: "https://github.com/manncz/stat-331-s26"
  repo-url: https://github.com/manncz/stat-331-s26
  repo-actions: [issue]

  page-footer:
    right: "This page is built with ❤️️ and [Quarto](https://quarto.org/)."
    left: "Built by Charlotte Mann, adapted from materials by Allison Theobold, Emily Robinson, Zoe Rehnberg, and Kelly Bodwin."
    background: "#bfd3e6"

  sidebar:
    background: "#8c96c6"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/manncz/stat-331-s26
        text: "GitHub organization"
      - icon: person-fill
        href: https://canvas.calpoly.edu
        text: "Cal Poly Canvas"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-info/syllabus-s26.qmd
            text: Syllabus
          # - href: course-materials/course-support.qmd
          #   text: Support
          - href: index.qmd
            text: Schedule
          - href: course-info/course-resources.qmd
            text: R Resources

format:
  html:
    theme:
      light: [cosmo, style/stat331.scss]
      dark: [cosmo, style/stat331.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    linkcolor: "#8856a7"
#    highlight-style: a11y-dark

editor: source
